  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: "toilaatmin@gmail.com"
      password: "laijaybhzvszxfdz"
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true